version: '3.8'

services:
  faiss-service:
    build: ./python-service
    ports:
      - "5000:5000"
    environment:
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}
    volumes:
      - ./index:/app/index  # Mount your FAISS index directory
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  nextjs-app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}
      - SERPAPI_API_KEY=${SERPAPI_API_KEY}
      - PYTHON_SERVICE_URL=http://faiss-service:5000
    depends_on:
      - faiss-service
    restart: unless-stopped
